name = "uEST2D"
uuid = "5fac7b1e-0744-40c0-a569-b2aace50f74f"
authors = ["Alex Nunn <alex.nunn@pm.me> and contributors"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
DifferentialEquations = "7"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
